version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_ecr:
    executor: clair/default
    steps:
    - run: $(aws ecr get-login --region ca-central-1 --no-include-email)
    - clair/scan:
        image: 848446468820.dkr.ecr.ca-central-1.amazonaws.com/ssm-session:amazonssh
workflows:
  test:
    jobs:
    - scan_ecr        
